### ISSUE TITLE
Rename 'schema' arguments to 'databaseSchema'

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CemConnector#32]
In HADES we tend to refer to 'databaseSchema' instead of 'schema', because of ambiguity about these terms in various DBMSs. (see [here](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html#schemas-and-databases)). Could all 'schema' arguments in `CemConnector` be renamed to 'databaseSchema' arguments? For example, `cemSchema` could be called `cemDatabaseSchema` [here](https://github.com/OHDSI/CemConnector/blob/1c837d26ee8b4ae262136670dca988f7f8ad683f/R/Connection.R#L31).

**Comment by azimov** [comment]
This is now fixed in the develop branch, will be included in next release
