### ISSUE TITLE
OHDSI public CEMConnector API instance

### ISSUE THREAD

**Issue by azimov** [OHDSI/CemConnector#8]
This is the overall objective; to allow anyone anywhere to query an open CEM project. Will need to consider scaling, hosting and security (e.g. rate limiting requests, stopping DDOS etc).

**Comment by ablack3** [comment]
I think a publicly available API would be really helpful and perhaps make it easier for researchers to use empirical calibration.

**Comment by azimov** [comment]
Discussing this with @cknoll, we think an appropriate way to do this would be to have the plumber instance secured behind WebApi that forwards requests to the plumber API.

For this to work on the client end we will need to support adding the atlas security tokens to request headers, using ROhdsiWebApi to handle the atlas security. For the public ATLAS the user currently needs to copy a bearer token from their browser to do this, though there are plans to support API tokens in the near future.

@leeevans would you like to set up a meeting about how to manage this service?

**Comment by leeevans** [comment]
@azimov I'm available for a call to discuss this with you and @cknoll on Wednesday afternoon or Thursday this week. 

Please send me a meeting invite. 

I think it would be very helpful to have Chris on the call for input on the WebAPI changes needed and how the WebAPI and plumber instance are going to communicate.
