### ISSUE TITLE
Request change in title case for consistency

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CemConnector#9]
I know there are several interpretations of camel case. In HADES R packages until now we've only capitalized the first letter of an abbreviation. For example, it's 'SqlRender' not 'SQLRender', 'Cyclops', not 'CYCLOPS', and 'ROhdsiWebApi', not 'ROHDSIWebAPI'.

Could the name therefore be changed to 'CemConnector'?

**Comment by azimov** [comment]
Fixed in develop branch.
